name: Trigger auto deployment for omano-crm-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/omano-crm-api-AutoDeployTrigger-33f0630d-0aeb-41cc-9c19-ca0806e44097.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.OMANOCRMAPI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ca296626e247acr.azurecr.io
          registryUsername: ${{ secrets.OMANOCRMAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.OMANOCRMAPI_REGISTRY_PASSWORD }}
          containerAppName: omano-crm-api
          resourceGroup: lab02-rg
          imageToBuild: ca296626e247acr.azurecr.io/omano-crm-api:${{ github.sha }}
          
            

     

